# -*- coding: utf-8 -*-
"""calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1077lWdVty7SO5Hdc4YCH7ZmK09qndBsJ
"""

def calculator(op1,op2,opr):
  match opr:
    case "+":
      result=op1+op2
      return result
    case "-":
      result=op1-op2
      return result
    case "*":
      result=op1*op2
      return result
    case "/":
      try:
        result=op1/op2
        return result
      except ZeroDivisionError:
        print("Error: Division by zero occured")
    case _:
      print("Invalid operator")

op1=float(input("Enter first operand:"))
op2=float(input("Enter second operand:"));
opr=input("Enter operator(+,-,*,/):")
print("The result is", calculator(op1,op2,opr))