# -*- coding: utf-8 -*-
"""wordcounter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p1GBcW_AW5YLJqMB1fCaksRyC8IDu6Yb
"""

text=input("Enter the string:")
word=text.split()
print("Total no of words is", len(word))
unique_words=set(word)
print("Total no of unique words is", len(unique_words))
from collections import Counter
frequency=Counter(word)
print(frequency)